#!/usr/bin/env bash

install_apt() {
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' $@
}

packages='
  curl
  ack-grep
  build-essential
  cmake
  doxygen
  exuberant-ctags
  colordiff
  awesome
  awesome-extra
  xsel
  openssh-server
  gnupg
  keychain
  nmap
  autossh
  vim-nox
  mutt-patched
  enscript
  urlview
  tmux
  scrot
  firefox
  virtualbox-4.3
'

# add virtualbox repo
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | \
  sudo apt-key add -
echo 'deb http://download.virtualbox.org/virtualbox/debian saucy contrib' \
  | sudo tee /etc/apt/sources.list.d/virtualbox.list

sudo apt-get update
install_apt $packages
