#!/usr/bin/env bash

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
  brew cask install "${@}" 2> /dev/null
}

installcask firefox
installcask dropbox
installcask iterm2
installcask transmission
installcask virtualbox
installcask vlc
installcask little-snitch
installcask skype
installcask tunnelblick
installcask xquartz
installcask vagrant
installcask flash
