#!/usr/bin/env bash

# Install docker
curl -sL https://get.docker.io/ | sudo sh
sudo adduser $USER docker

# Install docker-compose
curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` \
  | sudo tee /usr/local/bin/docker-compose > /dev/null
chmod 755 /usr/local/bin/docker-compose
