#!/usr/bin/env bash

ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"

brew update
brew upgrade

brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
brew install bash
brew install wget --enable-iri

# Install more recent versions of some OS X tools
# brew tap homebrew/dupes
# brew install homebrew/dupes/vim
# brew install homebrew/dupes/screen

brew install ack
brew install git
#brew install imagemagick
brew install node
# brew tap homebrew/versions
# brew install lua52

brew install macvim --override-system-vim
brew install cmake
brew install hub
brew install wemux
brew install autossh
brew install doxygen --with-dot --with-doxywizard
# brew install sdl2
# brew install sdl2_image
# brew install sdl2_mixer
# brew install sdl2_net
# brew install sdl2_ttf

# Remove outdated versions from the cellar
brew cleanup

brew linkapps --local
