#!/usr/bin/env bash
set -eu

dirname=$(cd $(dirname "$0") && pwd)

cd ${dirname}

files=$(ls | egrep -v 'README|make-symlinks|docker*')

for file in $files ; do
  echo "Symlinking ${file}"
  rm -f $HOME/.${file}
  ln -sf "${dirname}/${file}" "$HOME/.${file}"
done
